apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: miz-oki-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Maximum number of instances
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      serviceAccountName: miz-oki-service-account
      containers:
      - image: gcr.io/PROJECT_ID/miz-oki-app:latest
        name: miz-oki-app
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GCP_PROJECT_ID
          value: PROJECT_ID
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: INFO
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3